# Generated by Django 5.2.17 on 2026-10-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
