# Generated by Django 5.2.17 on 2026-10-08 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_otpemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('inscription', 'Inscription'), ('publication', 'Publication créée'), ('commentaire', 'Commentaire'), ('signalement', 'Signalement envoyé'), ('suspension', 'Suspension / bannissement'), ('mot_de_passe', 'Mot de passe modifié')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('appareil', models.CharField(blank=True, max_length=200)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': "journal d'activité",
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['user', '-cree_le'], name='comptes_act_user_id_29599a_idx'), models.Index(fields=['action', '-cree_le'], name='comptes_act_action_20a105_idx'), models.Index(fields=['-cree_le'], name='comptes_act_cree_le_4b9f27_idx')],
            },
        ),
    ]
