# Generated by Django 5.2.17 on 2026-10-09 18:08

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCompte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.CharField(max_length=255, unique=True)),
                ('appareil', models.CharField(blank=True, max_length=200)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_activite', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_compte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-derniere_activite', '-cree_le'],
                'indexes': [models.Index(fields=['user', 'active', '-derniere_activite'], name='comptes_ses_user_id_3b3dc5_idx')],
            },
        ),
    ]
