# Generated by Django 5.2.17 on 2026-10-09 19:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_sessioncompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lecture_seule',
            field=models.BooleanField(default=False, help_text='Le compte peut consulter le contenu, mais pas créer ni modifier de données.'),
        ),
        migrations.CreateModel(
            name='NoteInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=2000)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_internes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BadgeUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ancien_verifie', 'Ancien vérifié'), ('delegue', 'Délégué de classe'), ('administration', 'Administration')], max_length=24)),
                ('attribue_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('attribue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_attribues', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('user', 'type'), name='badge_utilisateur_unique')],
            },
        ),
    ]
