# Generated by Django 5.2.17 on 2026-10-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0003_publication_image_hauteur_publication_image_largeur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publications', models.CharField(choices=[('immediat', 'Immediat'), ('quotidien', 'Quotidien'), ('desactive', 'Desactive')], default='immediat', max_length=10)),
                ('likes', models.BooleanField(default=True)),
                ('commentaires', models.BooleanField(default=True)),
                ('amis', models.BooleanField(default=True)),
                ('discussions', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefs_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('publication', 'Publication'), ('like', 'Like'), ('commentaire', 'Commentaire'), ('demande_ami', 'Demande Ami'), ('ami_accepte', 'Ami Accepte'), ('invitation', 'Invitation'), ('invitation_acceptee', 'Invitation Acceptee'), ('resume', 'Resume')], max_length=20)),
                ('nb', models.PositiveIntegerField(default=1)),
                ('lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifie_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publications.publication')),
            ],
            options={
                'indexes': [models.Index(fields=['destinataire', '-modifie_le'], name='notificatio_destina_8f4e07_idx'), models.Index(fields=['destinataire', 'lue'], name='notificatio_destina_d40d57_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('web', 'Web'), ('fcm', 'Fcm')], max_length=5)),
                ('cible', models.TextField()),
                ('cles', models.JSONField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('echecs', models.PositiveSmallIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'actif'], name='notificatio_user_id_991664_idx')],
                'constraints': [models.UniqueConstraint(fields=('cible',), name='push_cible_unique')],
            },
        ),
    ]
