# Generated by Django 5.2.17 on 2026-10-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('publication', 'Publication'), ('like', 'Like'), ('commentaire', 'Commentaire'), ('demande_ami', 'Demande Ami'), ('ami_accepte', 'Ami Accepte'), ('invitation', 'Invitation'), ('invitation_acceptee', 'Invitation Acceptee'), ('resume', 'Resume'), ('avertissement', 'Avertissement')], max_length=20),
        ),
    ]
