# Generated by Django 5.2.17 on 2026-10-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
    ]
