# Generated by Django 5.2.17 on 2026-10-02 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('filiere', models.CharField(blank=True, max_length=80)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='scolarite.cycle')),
            ],
            options={
                'ordering': ['cycle__ordre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.PositiveSmallIntegerField()),
                ('annee_fin', models.PositiveSmallIntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scolarites', to='scolarite.classe')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scolarites', to='profils.profil')),
            ],
            options={
                'ordering': ['annee_debut'],
            },
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('cycle', 'nom', 'filiere'), name='classe_unique'),
        ),
        migrations.AddIndex(
            model_name='scolarite',
            index=models.Index(fields=['classe', 'annee_debut', 'annee_fin'], name='scolarite_s_classe__f77ee8_idx'),
        ),
        migrations.AddConstraint(
            model_name='scolarite',
            constraint=models.CheckConstraint(condition=models.Q(('annee_fin__gte', models.F('annee_debut'))), name='scolarite_annees_ok'),
        ),
        migrations.AddConstraint(
            model_name='scolarite',
            constraint=models.UniqueConstraint(fields=('profil', 'classe', 'annee_debut'), name='scolarite_unique'),
        ),
    ]
