# Generated by Django 5.2.15 on 2026-10-08 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0004_profil_whatsapp_profil_whatsapp_visibilite'),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lycee', models.CharField(choices=[('moderne', 'Lycée moderne'), ('technique', 'Lycée technique')], max_length=12)),
                ('nom', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['type_lycee', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ParcoursBrouillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.PositiveSmallIntegerField(default=0)),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modifie_le'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='scolarite',
            name='scolarite_annees_ok',
        ),
        migrations.AlterField(
            model_name='scolarite',
            name='annee_fin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='scolarite',
            constraint=models.CheckConstraint(condition=models.Q(('annee_fin__isnull', True), ('annee_fin__gte', models.F('annee_debut')), _connector='OR'), name='scolarite_annees_ok'),
        ),
        migrations.AddConstraint(
            model_name='filiere',
            constraint=models.UniqueConstraint(fields=('type_lycee', 'nom'), name='filiere_type_nom_unique'),
        ),
        migrations.AddField(
            model_name='classe',
            name='filiere_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='scolarite.filiere'),
        ),
        migrations.AddField(
            model_name='parcoursbrouillon',
            name='profil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcours_brouillon', to='profils.profil'),
        ),
    ]
