# Generated by Django 5.2.17 on 2026-10-02 22:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('annee_sortie', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950)])),
                ('onboarding_termine', models.BooleanField(default=False)),
                ('visibilite_profil', models.CharField(choices=[('tous', 'Tout le monde'), ('amis', 'Mes amis'), ('personne', 'Personne')], default='tous', max_length=10)),
                ('visibilite_parcours', models.CharField(choices=[('tous', 'Tout le monde'), ('amis', 'Mes amis'), ('personne', 'Personne')], default='tous', max_length=10)),
                ('visibilite_situation', models.CharField(choices=[('tous', 'Tout le monde'), ('amis', 'Mes amis'), ('personne', 'Personne')], default='tous', max_length=10)),
                ('qui_peut_inviter', models.CharField(choices=[('tous', 'Tout le monde'), ('amis', 'Mes amis'), ('personne', 'Personne')], default='tous', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SituationActuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('emploi', 'Emploi'), ('etudes', 'Études / formation'), ('recherche', "Recherche d'emploi"), ('autre', 'Autre')], db_index=True, default='autre', max_length=10)),
                ('poste', models.CharField(blank=True, max_length=120)),
                ('entreprise', models.CharField(blank=True, max_length=120)),
                ('secteur', models.CharField(blank=True, max_length=120)),
                ('ville_emploi', models.CharField(blank=True, max_length=100)),
                ('depuis', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('independant', models.BooleanField(default=False)),
                ('type_formation', models.CharField(blank=True, choices=[('universite', 'Université'), ('ecole', 'École supérieure'), ('professionnelle', 'Formation professionnelle'), ('autre', 'Autre')], max_length=20)),
                ('etablissement', models.CharField(blank=True, max_length=160)),
                ('faculte', models.CharField(blank=True, max_length=160)),
                ('diplome', models.CharField(blank=True, max_length=120)),
                ('niveau', models.CharField(blank=True, max_length=60)),
                ('annee_debut', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('annee_fin_prevue', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lieu_etudes', models.CharField(blank=True, max_length=120)),
                ('objectif', models.CharField(blank=True, choices=[('emploi', 'Emploi'), ('stage', 'Stage'), ('formation', 'Formation')], max_length=10)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations', to='profils.domaine')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='situation', to='profils.profil')),
            ],
        ),
    ]
