# Generated by Django 5.2.17 on 2026-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0002_profil_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='photo_s',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
