# Generated by Django 5.2.15 on 2026-10-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0003_profil_photo_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='profil',
            name='whatsapp_visibilite',
            field=models.CharField(choices=[('tous', 'Tout le monde'), ('amis', 'Mes amis'), ('personne', 'Personne')], default='amis', max_length=10),
        ),
    ]
