# Generated by Django 5.2.17 on 2026-10-09 16:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0004_profil_whatsapp_profil_whatsapp_visibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='date_anniversaire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhotoGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galerie/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='profils.profil')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
