# Generated by Django 5.2.17 on 2026-10-09 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0005_profil_date_anniversaire_photogalerie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadeauAnniversaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_bon', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeaux_anniversaire', to='profils.profil')),
            ],
            options={
                'ordering': ['-cree_le', '-pk'],
            },
        ),
    ]
