# Generated by Django 5.2.17 on 2026-10-04 20:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussions', '0001_initial'),
        ('publications', '0003_publication_image_hauteur_publication_image_largeur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cible', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('publication', 'Publication'), ('conversation', 'Conversation')], max_length=12)),
                ('motif', models.CharField(choices=[('harcelement', 'Harcèlement ou intimidation'), ('contenu_inapproprie', 'Contenu inapproprié'), ('faux_profil', 'Faux profil'), ('spam', 'Spam ou publicité'), ('autre', 'Autre')], max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=500)),
                ('extrait', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('ignore', 'Ignoré')], db_index=True, default='nouveau', max_length=10)),
                ('decision', models.CharField(blank=True, max_length=200)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_faits', to=settings.AUTH_USER_MODEL)),
                ('conversation_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='discussions.conversation')),
                ('publication_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publications.publication')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['statut', '-cree_le'], name='signalement_statut_e8dd85_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('type_cible', 'utilisateur')), fields=('auteur', 'utilisateur_cible'), name='signalement_user_unique'), models.UniqueConstraint(condition=models.Q(('type_cible', 'publication')), fields=('auteur', 'publication_cible'), name='signalement_pub_unique'), models.UniqueConstraint(condition=models.Q(('type_cible', 'conversation')), fields=('auteur', 'conversation_cible'), name='signalement_conv_unique')],
            },
        ),
    ]
