# Generated by Django 5.2.17 on 2026-10-09 16:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalement',
            name='alerte_seuil',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signalement',
            name='contexte',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='commentaire',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='motif',
            field=models.CharField(choices=[('harcelement', 'Harcèlement ou intimidation'), ('contenu_inapproprie', 'Contenu inapproprié'), ('faux_profil', 'Faux profil'), ('spam', 'Spam ou publicité'), ('autre', 'Autre'), ('bug', 'Bug'), ('suggestion', 'Suggestion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='type_cible',
            field=models.CharField(choices=[('utilisateur', 'Utilisateur'), ('publication', 'Publication'), ('conversation', 'Conversation'), ('retour', 'Retour de test')], max_length=12),
        ),
        migrations.CreateModel(
            name='ConfigurationSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouton_actif', models.BooleanField(default=True)),
                ('ouvert_a_tous', models.BooleanField(default=True)),
                ('utilisateurs_autorises', models.ManyToManyField(blank=True, related_name='autorisations_support', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuration du support',
                'verbose_name_plural': 'configuration du support',
            },
        ),
        migrations.CreateModel(
            name='PieceJointeSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='signalements/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'mp4', 'webm', 'mov'])])),
                ('type_contenu', models.CharField(max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='signalements.signalement')),
            ],
        ),
    ]
