# Generated by Django 5.2.17 on 2026-10-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0002_signalement_adresse_ip_signalement_alerte_seuil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=2000)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_support', to='signalements.signalement')),
            ],
            options={
                'ordering': ['cree_le', 'pk'],
            },
        ),
    ]
