# Generated by Django 5.2.17 on 2026-10-02 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/%Y/%m/')),
                ('statut', models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon')], db_index=True, default='publie', max_length=12)),
                ('apercu_public', models.BooleanField(default=True)),
                ('est_masque', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='publications.publication')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=1000)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_publications', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='publications.publication')),
            ],
            options={
                'ordering': ['cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['statut', 'est_masque', '-cree_le'], name='publication_statut_50fae2_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['auteur', 'statut', '-cree_le'], name='publication_auteur__3a9655_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('publication', 'user'), name='unique_like_par_utilisateur'),
        ),
        migrations.AddIndex(
            model_name='commentaire',
            index=models.Index(fields=['publication', 'cree_le'], name='publication_publica_4c7661_idx'),
        ),
    ]
