# Generated by Django 5.2.17 on 2026-10-03 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like_par_utilisateur',
        ),
        migrations.RemoveIndex(
            model_name='publication',
            name='publication_statut_50fae2_idx',
        ),
        migrations.RemoveIndex(
            model_name='publication',
            name='publication_auteur__3a9655_idx',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='modifie_le',
        ),
        migrations.RemoveField(
            model_name='like',
            name='cree_le',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='est_masque',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='masque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='extrait',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='masquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='nb_commentaires',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='nb_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='publie_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='texte',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publiée')], default='brouillon', max_length=10),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['statut', 'masquee', '-publie_le'], name='publication_statut_5ad3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['auteur', '-cree_le'], name='publication_auteur__e737f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('publication', 'user'), name='like_unique'),
        ),
    ]
