# Generated by Django 5.2.17 on 2026-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_commentaire_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_hauteur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='image_largeur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='image_m',
            field=models.ImageField(blank=True, null=True, upload_to='publications/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='image_s',
            field=models.ImageField(blank=True, null=True, upload_to='publications/%Y/%m/'),
        ),
    ]
