# Generated by Django 5.2.17 on 2026-10-09 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date_programmee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('programmee', 'Programmée'), ('publie', 'Publiée')], default='brouillon', max_length=10),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['statut', 'date_programmee'], name='publication_statut_6ca31d_idx'),
        ),
    ]
