# Generated by Django 5.2.17 on 2026-10-02 22:40

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='attente', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('repondue_le', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['destinataire', 'statut'], name='amis_amitie_destina_a428b9_idx'), models.Index(fields=['demandeur', 'statut'], name='amis_amitie_demande_7f7576_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('demandeur', models.F('destinataire')), _negated=True), name='amitie_pas_soi_meme'), models.UniqueConstraint(django.db.models.functions.comparison.Least('demandeur', 'destinataire'), django.db.models.functions.comparison.Greatest('demandeur', 'destinataire'), name='amitie_paire_unique')],
            },
        ),
        migrations.CreateModel(
            name='Blocage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocages_recus', to=settings.AUTH_USER_MODEL)),
                ('bloqueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocages_faits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['bloque'], name='amis_blocag_bloque__fbc239_idx')],
                'constraints': [models.UniqueConstraint(fields=('bloqueur', 'bloque'), name='blocage_unique'), models.CheckConstraint(condition=models.Q(('bloqueur', models.F('bloque')), _negated=True), name='blocage_pas_soi_meme')],
            },
        ),
    ]
