# Generated by Django 5.2.17 on 2026-10-04 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('groupe', 'Groupe')], default='direct', max_length=10)),
                ('paire_cle', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('dernier_message_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('attente', 'Attente'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee'), ('annulee', 'Annulee')], default='attente', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('repondue_le', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['destinataire', 'statut', '-cree_le'], name='discussions_destina_9186dc_idx'), models.Index(fields=['demandeur', 'statut'], name='discussions_demande_6cd1bc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('demandeur', models.F('destinataire')), _negated=True), name='invitation_pas_soi_meme'), models.UniqueConstraint(condition=models.Q(('statut', 'attente')), fields=('demandeur', 'destinataire'), name='invitation_attente_unique')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=2000)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussions.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'id'], name='discussions_convers_df40d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dernier_lu', models.BigIntegerField(default=0)),
                ('archive', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='discussions.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'archive'], name='discussions_user_id_164138_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='participant_unique')],
            },
        ),
    ]
