# Generated by Django 5.2.17 on 2026-10-05 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duree_vocale',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='en_reponse_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='discussions.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='messages/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='nom_fichier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='taille_fichier',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('fichier', 'Fichier'), ('vocal', 'Vocal')], default='texte', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='texte',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='ReactionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=8)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='discussions.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['message'], name='discussions_message_db8cc9_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='reaction_unique')],
            },
        ),
    ]
