# Generated by Django 5.2.17 on 2026-10-09 19:36

from django.db import migrations, models


def creer_configuration_par_defaut(apps, schema_editor):
    configuration = apps.get_model("discussions", "ConfigurationDiscussion")
    configuration.objects.using(schema_editor.connection.alias).get_or_create(pk=1)


def supprimer_configuration_par_defaut(apps, schema_editor):
    configuration = apps.get_model("discussions", "ConfigurationDiscussion")
    configuration.objects.using(schema_editor.connection.alias).filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_one_reaction_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloquer_captures_ecran', models.BooleanField(default=False, help_text='Dans l’application Android, bloque les captures et l’enregistrement d’écran pendant une discussion.')),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(creer_configuration_par_defaut, supprimer_configuration_par_defaut),
    ]
