from django.urls import path

from . import views

urlpatterns = [
    path("discussions/configuration-securite/", views.ConfigurationSecuriteView.as_view()),
    path("discussions/apercu-lien/", views.ApercuLienView.as_view()),
    path("discussions/invitations/",
         views.InvitationsView.as_view()),
    path("discussions/invitations/<int:pk>/accepter/",
         views.InvitationActionView.as_view(), {"action": "accepter"}),
    path("discussions/invitations/<int:pk>/refuser/",
         views.InvitationActionView.as_view(), {"action": "refuser"}),
    path("discussions/invitations/<int:pk>/",
         views.InvitationAnnulerView.as_view()),
    path("discussions/compteurs/",
         views.CompteursView.as_view()),
    path("conversations/",
         views.ConversationsView.as_view()),
    path("conversations/<int:pk>/",
         views.ConversationDetailView.as_view()),
    path("conversations/<int:pk>/messages/",
         views.MessagesView.as_view()),
    path("conversations/<int:pk>/messages/media/",
         views.MessagesMediaView.as_view()),
    path("conversations/<int:pk>/messages/<int:msg_id>/modifier/",
         views.MessageActionView.as_view()),
    path("conversations/<int:pk>/messages/<int:msg_id>/suppression/",
         views.MessageSuppressionView.as_view()),
    path("conversations/<int:pk>/messages/<int:msg_id>/favori/",
         views.MessageFavoriView.as_view()),
    path("conversations/<int:pk>/messages/<int:msg_id>/epingler/",
         views.MessageEpingleView.as_view()),
    path("conversations/<int:pk>/messages/<int:msg_id>/transferer/",
         views.MessageTransfertView.as_view()),
    path("conversations/<int:pk>/messages/<int:msg_id>/",
         views.MessageActionView.as_view()),
    path("conversations/<int:pk>/messages/<int:msg_id>/reactions/",
         views.ReactionView.as_view()),
    path("conversations/<int:pk>/lu/",
         views.LuView.as_view()),
]
